version: '3'

services:
  starsoft:
    image: bitnami/postgresql:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432 
    environment:
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}
volumes:
  pgdata:
